### ISSUE TITLE
这个是api几的呀

### ISSUE THREAD

**Issue by pansida** [seagazer/listen#1]
能不能把文档写详细一些呀

**Comment by seagazer** [comment]
> 能不能把文档写详细一些呀

当前版本为API10，后续会升级适配API11，以下为编译环境：IDE版本：4.0release（4.0.0.600） + full-SDK版本：4.0.10.16，在DAYU200的4.1release版本（4.1.7.6）上运行验证
工程内部有mockTest，内部预置了媒体和歌词文件，以及推送脚本供测试体验
