### ISSUE TITLE
关于歌词样式

### ISSUE THREAD

**Issue by 17683813062** [seagazer/listen#2]
当前正在唱的歌词，有能从左到右逐渐高亮的功能吗？

**Comment by seagazer** [comment]
> 当前正在唱的歌词，有能从左到右逐渐高亮的功能吗？

你好，卡拉ok这种逐字歌词，本库目前版本还不支持。如果基于5.0的话，是可以考虑移植android库来实现，实现原理都是一样的，目前Api12提供的能力基本上可以满足复杂自绘组件的开发需求。
